### ISSUE TITLE
Bot often gets stuck at end of raid and doesnt refresh

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/SarasaBot#169]
![image](https://user-images.githubusercontent.com/36133340/40174077-dfb8bcf0-59cb-11e8-8c03-4b55eb10060e.png)

Is there a fix to this problem, as for the past week, the bot seems to stop at some raids without refreshing. It seems to happen just when a boss dies when pressing attack at the same time, which is a common occurrence in m2 raids due to how fast they get burned down

The bot wont return with the line "no response received after pressing the attack button for an abnormally long time" thus will remain stuck in the position

Current chromium version 66.0.3359.139 (Official Build) (64-bit)

**Comment by CorrinKrow** [comment]
This is becoming a regular occurence with the bot getting stuck every 30 minutes or so. I have been using viramate shortcuts
Is there a fix planned for this?
@Masuzu

**Comment by Masuzu** [comment]
I am sorry for the late reply,
I will release a mitigation for this issue in the next hours.

**Comment by Masuzu** [comment]
This is now addressed in v1.9.5

**Comment by CorrinKrow** [comment]
![image](https://user-images.githubusercontent.com/36133340/40292398-02f96a58-5cc3-11e8-9267-726090b441e0.png)
The issue still occurs in 1.9.5
